name: aqua_safe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2
  geolocator: ^9.0.2
  # permission_handler: ^10.4.1
  timeago: ^3.0.2
  connectivity_plus: ^6.1.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0
  # flutter_background: ^1.2.0
  # background_fetch: ^1.3.7
  # flutter_background_geolocation: ^4.16.8
  permission_handler: ^11.0.1
  geocoding: ^2.2.0

  # for hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.0
  sensors_plus: ^6.1.0
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  mockito: ^5.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

  assets:
    - .env
    - assets/logo.png
    - assets/fish_icon.png
    - assets/weather.png
    - assets/marker_vessel.png
    - assets/navigation_icon.png
