name: aqua_safe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2 # For Bluetooth communication
  geolocator: ^9.0.2
  # location: ^5.0.0 # To get GPS data dynamically

  # for hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # for hive
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
    - assets/fish_icon.png
    - assets/weather.png
